### ISSUE TITLE
Do we want Board representation?

### ISSUE THREAD

**Issue by mcollina** [nodejs/bootstrap#17]
This is a spin-off discussion from https://github.com/nodejs/bootstrap/pull/12.

I would like to ask everyone in this group what kind of Board representation do we want or need. Currently the project has 3 Board seats: 1 CommComm Director, 1 TSC Director, 1 individual. The Board is currently composed of 10 members.
In a multi-project foundation, our current setup might not work. 

Some questions from @rubys:

* Do we want only Node.js to have board representation?
* Do we want each and every project, no matter how big or how small, to have board representation? 
* Do we want to have a single person to represent all projects? 

If none of the above, what exactly do we want?

To this regard, I would kindly ask @MylesBorins @hackygolucky @jasnell @rvagg (as the directors that have been elected by the TSC/CommComm) to share their experience as directors.

**Comment by jasnell** [comment]
The merger poll that I sent out to the TSC and CommComm is not quite completed yet, but we have 24 responses out of 34 possible (there are actually 26 responses but 2 non top level committee folks voted and I'll be removing their responses from the results when completed) ... that said, here are the current results on this specific question:

![image](https://user-images.githubusercontent.com/439929/47294186-2b7fcb80-d5c1-11e8-9436-01d6fafe2a9c.png)

I think that makes it pretty clear. 84.6% of respondents believe Node.js *must* have board representation, with the largest majority of those *strongly* agreeing.

**Comment by dylans** [comment]
I think in terms of board voting rights, the projects should be represented and it was probably a mistake of the JSF to not do this as it led to the perception of less transparency and less of a voice for the projects. The preceding Dojo and jQuery foundations both had substantial project representation on the board fwiw.

I would argue for multiple board seats for the projects. 1 for Node.js given its size, and 1 or 2 to represent the other projects via some sort of vote from the leads of all of the projects (I think 1 person to represent 30-some projects including Node.js is a bit much to ask of that one person, though it could be achieved), and maybe others depending on how things like CommComm and TSC end up.

Or there might be an alternative where projects are sorted into a few groups (strawman: Node.js gets grouped with things like NodeRed and IoT/embedded projects, the various client-side JS projects get grouped together, and maybe the testing+linting projects in a third group, and from that you get 3 groups to each vote on a board rep).

In terms of non-voting rights (e.g. option to attend but do not vote), in terms of transparency I think you open that up to one person from each project.

The follow-up question that may get asked (or at least which I don't know the answer to): Do the board meetings happen online or in person. If the latter, that may impact the ability for the non-member to afford attending meetings unless the foundation is expected to cover travel costs.

**Comment by rubys** [comment]
> Currently the project has 3 Board seats: 1 CommComm Director, 1 TSC Director, 1 individual. The Board is currently composed of 10 members.

I count [11](https://foundation.nodejs.org/about/leadership).  Not that the actual number matters all that much.

I sense apportioning fractional directors up front across projects is likely to be a problem, so how about splitting this into two parts?

First part: determining the number of directors that come from the projects.  Perhaps this could be a fixed ratio of the corporate members to project members?  Say, start with the number of corporate members and divide by three and round up (or perhaps divide by two and round down).  This number to be reevaluated at a fixed time (perhaps annually).

Second part: determining who to elect.  Perhaps a foundation wide election where all collaborators of any project is eligible to cast a single vote?  If a process like [STV}(https://wiki.apache.org/general/BoardVoting) is used, large projects will get their proportional share but generally not much more.  I encourage viewing and reading the links in the "How Are Votes Counted?" section of that page.

**Comment by mcollina** [comment]
> First part: determining the number of directors that come from the projects. Perhaps this could be a fixed ratio of the corporate members to project members? Say, start with the number of corporate members and divide by three and round up (or perhaps divide by two and round down). This number to be reevaluated at a fixed time (perhaps annually).

I like this approach. This is simple.

> Second part: determining who to elect. Perhaps a foundation wide election where all collaborators of any project is eligible to cast a single vote? If a process like STV is used, large projects will get their proportional share but generally not much more. I encourage viewing and reading the links in the "How Are Votes Counted?" section of that page.

This is where things gets tricky. I like an approach where large projects will get their share, but not much more. I'll need to study STV (which I didn't know).

Also, who can be nominated?

**Comment by MylesBorins** [comment]
Currently there are 12 board members, 3 of which are community representation.

**Comment by knolleary** [comment]
One of the challenges from the JSF side is the range of scales of each project. Projects do not have any direct representation on the board. Projects that have meet a [set of criteria](https://github.com/JSFoundation/TAC/blob/master/Project-Lifecycle.md#mentorship) can graduate out of 'mentorship' at which point they get to nominate a representative to the Technical Advisory Committee. The Chair of the TAC sits on the Board - which does mean, in the current structure, one person represents all 28 projects on the board - albeit indirectly via the TAC.  Of the 28 projects, only 2 have graduated and thus have representation on the TAC - leaving 26 projects without any representation.

The criteria for graduation are focussed on the size of the project's governing body and the diversity (in terms of organisations) of that body. It makes passing reference to other criteria in the project's original application, but doesn't spell out what they are. Some projects were grandfathered into the JSF and some we added as part of the foundation launch. As one of the latter, I have no idea what other criteria apply to Node-RED. 

If we want board representation to be reflective of a project's size, we need very clear criteria what we mean by size.
 - Is it the number of committers?
 - Is it the size of its governance body?
 - Is it some popularity metric?

Is a project that is maintained by a single developer but gets 10m downloads a week a bigger or smaller project than one that has 3+ different companies involved in its governance (as per graduation criteria), but only has 1000 downloads a week.

There is also the fundamental question of whether node.js should be considered 'just one of the projects' or as an exceptional entity within the foundation. I would suggest that, by pretty much any metric chosen, node.js would be considered a 'big' project and earn whatever representation that garners. That would keep everything on level playing field.

**Comment by jorydotcom** [comment]
I'm concerned that we're not looking at the problem in the right light in order to evaluate these proposed solutions. For the record, I'm not against project representation on the board, but I struggle to see how any of the options submitted thus far will prevent the issues that we've all raised on other threads. I think there's another side to the 'board seat' problem. Hear me out: 

**Projects want a seat at the board table because it guarantees that someone from the project has access to information from the board and a voice on the board to raise issues or concerns with the $Foundation.**

This is a very real need, but as @mcollina pointed out it doesn't scale - as the number of projects grow,  it becomes increasingly difficult to schedule meetings, reach quorum, and ensure everyone is familiar enough with an issue to take a vote on it. Further, a lot of the board's proceedings are going to be agnostic to the concerns of a given project (should we sponsor a conf? should this new project come in? should we renew our vendor relationship with LF? etc - while those items would be of interest to folks, they're also probably not something that projects will feel strongly enough about to weigh in on,  except in extreme circumstances).  We also get into the issue of what happens when a project representative on the board also happens to work at a member company who already has a seat at the board. Keeping track of the rules and relationships here could get tricky. I don't know of another software foundation or consortia that provides a seat at the board for every project, so there's not a lot of prior art I'm aware of for that organizational model. 

**The communication flow between the foundation boards and their projects has been less than ideal, and is the primary cause of concern during these merger conversations.** 

That said, both foundations ostensibly had board representation through different means. The JSF TAC chair is a member of the JSF board, and Node's TSC, CommComm & Individual directors are members of the Node Board. The communication issues were present despite some degree of access; so why is that? To briefly summarize my perception of that from the JSF side:
* Some projects expected and wanted more consistent engagement, which did not match the structure or resource limitations of the JSF. 
* The JSF relied on a 'nested hierarchy' for info to roll up to the board from projects via the TAC.
* The TAC chairperson, who is not paid by the foundation, has a busy full-time job outside of the day-to-day of the project communities, and focused their time on mentoring and assisting projects as needed.
* Almost everyone in the org is a volunteer with different projects - our day-to-day is focused on our communities, not the whole org. And also our jobs, which may be unrelated to our projects.
* The JSF ED, the foundation's only employee, was directed to focus on recruiting new members and mentoring a few new projects, leaving little time/bandwidth for existing projects.
* Regular updates to the projects wasn't made anyone's job. It was assumed that JSF news would reach people via social media channels or the occasional email thread.

The result was a lot of mis-set expectations and unmet needs, and it needs to be said that none of this was intentional or malicious. All of the points listed above can be easily solved - they just need to be addressed directly & transparently. I encourage the community directors from Node to think about why, despite having board seats, the community doesn't feel heard by the board. I imagine some of this is the same and some of it is different.

**Project board seats are an implementation detail; the problem it's meant to solve is communication and expectation-setting.**

So we could make some kind of arrangement where projects over a certain size get board seats, and maybe others are grouped in some capacity (how do you measure that, as @knolleary pointed out?) - but I fear we end up with the "trickle-down info" problem we had in the JSF, where not everyone was truly being represented. 
Or we could also have an [omsbuds-person](https://en.wikipedia.org/wiki/Ombudsman) for every project, or a group of projects, who is invited to attend board meetings and whose sole job is to report and advocate for their project. 
Or we could create a 'Reporter' officer position on the Board, whose job it is to do this legwork and make sure information is shared and gathered. 
Or we could create job descriptions for the "board seats" and have a people who serve on the board for their project commit to specific tasks for a certain term.
Or we could do all of the above. 

We're all very busy people, and good communication is really going to be everyone's job. Let's make sure the new system we create makes this as easy as possible and doesn't re-create the same issues.

**Comment by boneskull** [comment]
(Is there a "Foundations for Dummies" book?  Or even a TL;DR version thereof?  In other words...excuse my ignorance.)

I'm trying to understand why I'd want representation on a board.

- Where do the board's responsibilities begin and end?
- Could the responsibilities be minimized to such an extent that a seat would be of little use to a project?  Or is this not possible, since the board has influence upon the ED?
- Shouldn't the projects be working more with the foundation and its employees/volunteers itself, not its board?

**Comment by mcollina** [comment]
@knolleary 

> The Chair of the TAC sits on the Board - which does mean, in the current structure, one person represents all 28 projects on the board - albeit indirectly via the TAC. Of the 28 projects, only 2 have graduated and thus have representation on the TAC - leaving 26 projects without any representation.

This is more or less the situation that I would like to avoid. IMHO every project should have a direct line up and their member should feel represented and part of something bigger.

---

Well written @jorydotcom!

I think we have one of our first problem statements that we would like to solve:

> Projects want a seat at the board table because it guarantees that someone from the project has access to information from the board and a voice on the board to raise issues or concerns with the $Foundation.

> Project board seats are an implementation detail; the problem it's meant to solve is communication and expectation-setting.

Considering the fact that a significant amount of the work the Board do happens at closed doors, I fear the only way to guarantee that flow of information is to have a proper seat at the table. The TSC and CommComm do not have visibility on the 100% that gets discussed by the Board (some details are extremely confidential): we trust our representatives to act on behalf of the project. I fear that without some votes allocated to the projects, our voices will not be heard, and I know that all of our directors have been instrumental in growing the Node.js project because of their role. This has been far from perfect, but it works.
Even from a pure formal point of view, having a vote could send a meaningful signal.

----

@boneskull  It's perfectly OK for a project to not want to be involved, and to _not_ consume any Foundation resources. Express and Liibuv falls into this category.
If a projects needs anything from the Foundation to keep growing, it's fair to assume that they would like to check that their needs are met year after year if the funds are available. Especially if they cannot leave / or gather funds elsewhere.

The more funds a Foundation gathers, the more they can do things for the projects, the more the projects would like to check how that money is being spent. Bad marketing can be more harmful than no marketing at all. If the foundation cannot do anything for the projects - then why raising funds in the first place?

**Comment by rubys** [comment]
@mcollina my sense is that you are misunderstanding @boneskull question, and perhaps bringing in some of your own perspective - not that there is anything wrong with that, but I would like to tease apart the real question that we need to address.

Let's start with @jasnell's graph.  I read it as "without a common understanding of what the role of the board is, do you wish to be a part of the board (either directly or by proxy)".

My sense (by talking to people who are not on the board) is that the perception is that the board is where the action is (or at the very least, where the money flows from).  My experience (from being on a different board, and from the few board members that I have talked to) is that this either is not the case, or should not be the case.

This comes down to: is the board the place where decisions are made, or is it a place where decisions are ratified?  Is the board more like a loan officer or an ATM?  Is the money "their money" but if you make the case, they will begrudgingly let you have access to some?  Or is the money "your money" and the board's role is to ensure that you presented the right credentials and don't go beyond your limits?

In the ASF, we just kicked off our annual five year plan review, where I will be gathering input from each of the budget holders (generally non-directors, and those that happen to be directors will be contributing to this discussion with the Director "hat" taken off).  I will be leading this process, and am not currently a Director, and in fact, intentionally stepped down as Director when I toke on the role as President.

Early next year, we will follow this up with annual budgets.

A different model.  One that appears healthier.  One where people who want something from the foundation deal not with the board but with somebody who is pulling together a budget.  And once that budget is approved, work with accounting (again not the board).  The board's role in this is to approve the budget (mostly ATM style, as in did the people with the right credentials participate in the process?), and to review monthly reports from the Treasurer as to whether spending is going according to plan.

Circling back (and potentially putting words into @boneskull's mouth, but I don't think so give that what I believe I am saying is consistent with the words he posted): does wanting to be a beneficiary of being a part of this foundation require direct involvement with the board?

**Comment by jasnell** [comment]
> Let's start with @jasnell's graph. I read it as "without a common understanding of what the role of the board is, do you wish to be a part of the board (either directly or by proxy)".

My experience has been that Node.js top level committee members tend to have a higher than average understanding of what is happening at the board level than most. The desire to have representation on the board is not about being where the "action is" as we all have a fairly solid understanding that the decisions that directly affect the project happen at the collaborator level. It's about making sure the project has input into larger issues around the brand, legal, and financial issues when they arise.

**Comment by rubys** [comment]
> understanding of what is happening at the board level 

I focus on the word "is" in that sentence.  There seems to be a lot of angst over what "is" happening.  Perhaps there may be a better alternative?

> It's about making sure the project has input into larger issues around the brand, legal, and financial issues when they arise.

I read into this a presumption that these issues are perceived to be owned by the board.  Am I reading this correctly?  Would perhaps a better organization be one where these are spun off into separate functions with autonomy, where the board's role of one of oversight instead?

At the ASF, VP Brand happens to be a board member (though I will assert that his role as VP Brand is separate from his role as Director).  We currently have two people sharing the role of VP Legal, one is a Director and one in not.  Neither the ASF Treasurer nor VP Finance are Directors, though the Assistant Treasurer is.

I continue to assert that there is a different organizational model that may be a better fit for this proposed merged foundation.  All of the [ASF board minutes](https://whimsy.apache.org/board/minutes/) are published online, and I can walk people though this if there is interest.  I've also created a lot of automation around the process that I can help bring here.

**Comment by mcollina** [comment]
@rubys are 100% of ASF Board meetings public?

**Comment by rubys** [comment]
@mcollina short answer, no, but damn close.

Longer answer:

Every ASF Officer or ASF Member can attend any board meeting at the ASF.  These don't have direct analogized here, but every project has a chair which is an officer (and here is another case of where projects recommend a person to be chair and the board routinely ratifies that person, it is exceedingly rare for the board to name or replace a chair, and in those rare cases it is an exceptional circumstance).  ASF members also don't have an exact analogy here, it generally is a level above collaborator, so members of TAC or TSC and ConCom are a close match).  To give you an idea, we have 198 projects (each with an officer) and 730 members (clearly there is overlap between those two sets).  We also have various other officers, though pretty much all of them are members.

Second, the full agenda (which includes all officer reports) is available to all officers and members.  Per the above, that's over 800 people.  A small portion (as in 5% or less) is redacted.  This generally means things like the names of perspective sponsors, names of groups with which we have trademark issues, and names of perspective collaborators that have yet to be named.

Finally, there is something rare and exceptional, called executive session. That's where the board has a private meeting.  These tend to happen less than once a year, mostly to do things like electing executive officers (which sometimes is done privately, other times openly), and rarely (as in a once or twice a decade) to handle sensitive matters.  Most of these sessions are on the order of 15 minutes, an hour on the outside.

**Comment by rubys** [comment]
>  if the project were allowed more direct oversight over the use of the brand, that would also make it significantly less important to sit on the Board.

That's exactly the type of input we need.  Thanks!

My sense is that project representation doesn't scale, and any attempt to impose a rank ordering of projects (example: platinum vs gold vs silver) is counter productive.  That being said, I sense little to no pushback to having a percentage of board members being elected at large, and I can bring knowledge and tooling to solving that problem.

What does scale is delegation. The ASF has a Brand Management committee that reports not to the board but to the president.  The roster for that committee is stored in https://svn.apache.org/repos/private/committers/board/committee-info.txt, which isn't public, but is visible to the 6549 people who have commit rights to an ASF repository.  The Brand Management committee currently has 9 members, only two of which are current Directors.

I'll close by noting that Brand Management as a committee is not called out in the ASF bylaws.  What is described is the ability to create committees (and similar language is present in both the JSF and Node.js bylaws).  So this is an ability that the ASF makes productive use of, and is essentially "unexpressed DNA" in the Node and JS Foundations.

**Comment by MylesBorins** [comment]
Some insight from a current board member.

We currently have both a private and public session when we do meetings currently. Both sessions are an hour. The public session is broadcast on youtube but can only be attended by board members, LF staff, and invited guests.

We attempt to put as much in the public session as possible. The private session tends to be used for confidential discussion. At times this confidential discussion can be shared with the project, and board reps such as myself, @hackygolucky, or @williamkapke will officially ask the board for permission to share the results of the private discussion. Examples of this would be a high level view of a program while not discussing the budget.

The board does have subcommittees to discuss certain matters, and these subcommittees meetings are generally private. The main subcommittees I can think of at the moment are Legal, Financial, Marketing, and the subcommittee formed to discuss the merger.

My experience has been that if / when these things can be made public they will be, as you see with the merger subcommittee joining the bootstrap team. That being said some topics cannot be talked about with the same candor in a public setting. This is a tradeoff. As such many early ideas that need to be discussed with extreme candor can be introduced in a private setting and moved to a public setting at their earliest convenience.

Board members have expressed in the past a desire to create public sub-committees that are empowered by the board to make decisions, have a budget, and have community representation.

I personally believe that if we were to empower both a Cross Project Council (technical) and a C3 (community) with decision making authority and budget we would significantly reduce the need for direct project board representation. I'll even take it a step further and say that we likely should have foundation staff who's full time job it is to ensure that we execute on our decisions (a project / program manager).

Even if we were able to get the board representation we ask for, the time commitment is fairly large if you want to be an effective board member. The real long term solution to this would be to empower the projects to have budget, to be able to make decisions, and to have the foundation supply the adequate resources to make sure we execute. I don't think it is fair or strategic to rely on volunteers to execute on these important matters.

**Comment by rubys** [comment]
Reactions to @MylesBorins comment above:

1) I agree that the public/private is a tradeoff.  That being said, my sense is that the current "default closed" assumption of Node.js (as evidenced by the need to ask permission to share) vs a "default open" assumption (everything is sharable unless otherwise noted, the model for the ASF board minutes) does not serve the Node.js foundation well at this time.

2) The right model might not be for projects to have budgets but for departments (trademarks, marketing, conferences, etc) to have budgets, and to have projects participate in those committees.  

3) volunteers vs paid staff isn't as straightforward as you suggest.  I know some amazing volunteers who have been around for decades and continue to consistently contribute.  I know some paid staff that were let go, hired away, or resigned after months.  The closest I have come to a conclusion is that the split isn't between important and not-so-important, as between urgent and not-so-urgent.  If something needs a timely response, there should be paid staff responsible for that function.  There are many important functions that aren't urgent that can be handled by motivated volunteers.

**Comment by MylesBorins** [comment]
@rubys response to response

1) The default is to put things in the public session. When things are in the private session that is the only time we need to ask to share.

2) I was thinking it more like a larger cross project council had a budget and projects could request it... but I think we are getting into implementation details here... glad we are on the same page about it not being 'board business'

3) I agree with everything you stated. I was more thinking about things in terms of responsibility. That the execution on important matters should be the responsibility of a foundation employee whose performance review and job is dependent on executing.

**Comment by rubys** [comment]
Sorry, I can't resist injecting a little levity into this discussion.  ;-)

So node.js releases should be made by foundation employees?  Or node.js release aren't important?  Or...?

I'm old enough to remember when the conventional wisdom was that you couldn't trust open source as it was developed and maintained by volunteers.

P.S.  I still think that the public/private tradeoff choices that are being made need reexamining.

**Comment by mhdawson** [comment]
The urgent versus non-urgent resonates with me.  When an action needs immediate response it's a harder fit for volunteers.  It is hard for a volunteer to have the expectation to always be available and hard on those who are waiting for something urgent.

On the other hand we are very successful in trusting volunteers with very important areas/activities.

**Comment by boneskull** [comment]
Thanks everyone.

@rubys is correct in interpreting my awkwardly-worded question.  @mcollina It's not that I, as a project owner, *don't want to* leverage foundation resources; it's rather a question of "*what kind of board* would I want representation on?"

From the comments above, *if* the board's responsibilities and power are diminished, and projects are in control of their trademarks and destiny, and budgets are no longer "board business", *then* it sounds like a project owner wouldn't necessarily want to bother with board representation.

@jasnell's chart shows that project members want a seat at the board's table. 
 It doesn't answer the question of *why*.  Presumably, because *that's where you eat* if you're working with the current Node.js foundation.  :wink:

**Comment by jorydotcom** [comment]
After talking with folks in Vancouver and also reading some replies, it occurs to me that we may want to disambiguate what kind of Foundation we're talking about here. I'm picking up on some competing ideas of what a Foundation is so hopefully this is helpful context for folks (apologies to anyone for whom this info is not new):

The LF, Node, and JS Foundations are [501(c)(6)](https://www.irs.gov/charities-non-profits/other-non-profits/business-leagues) organizations that exist to promote the common interests of its members in open source software (or professional sports, or dentistry, or whatever the shared interest is). In practice this means marketing, branding, and PR work for key technologies, and for members' investment in said technologies (via case studies, certification, thought leadership, etc). 

When most people think of a non-profit foundation, they think of a [501(c)(3)](https://www.irs.gov/charities-non-profits/charitable-organizations/exempt-purposes-internal-revenue-code-section-501c3), which are tax-exempt charitable organizations that operate in the public interest. ASF & other, older open source software foundations are (c)(3)s, but the IRS has since changed its mind on that.*  

In the latter case, Board members are usually expected to raise a certain amount of funds or to contribute a certain amount of their own money to the foundation. In cases where the foundation takes public donations, there is often a board requirement that there are neutral advisory parties (people who don't stand to benefit in anyway) who are responsible for ensuring that the money is handled appropriately. Board membership here requires active engagement. 

In the former case, the board membership pattern both our organizations currently have is common practice - people or organizations pay money to become members of a group, associate their brand with that group, and promote or benefit from group membership in some (non- or indirectly commercial) way. Lots of times, board seats in these kinds of orgs are expected to be fairly procedural & not particularly active.

It seems like our community is looking for a blend of both approaches:

1. We want a board that is hands-off project work & direction, provides input when needed, and will hold the new ED & their staff accountable for delivering value to members + projects. I think this aligns with the expectations of the current boards as well.
1. We also want a board that is fairly distributing resources of the organization to the projects as needed (travel funds, promo items, etc) and/or available to assist in personnel issues (a tricky CoC violation, for example). I think it's hard for the board to play this role without being more engaged in the projects, and is _not_ what the current boards want to be doing. 

If I understand @boneskull & others correctly - they want to work with organization staff on the items in 2) and have a clear path to provide feedback for 1) without the meeting obligations of a board seat. If decisions around project funding and branding/promotion are moved out of the Board's work into separate top-level committees, and projects have clear representation on those groups, does that strike the right balance of @mcollina @jasnell @boneskull et al?

*personal opinion here: it would be great to write a purpose statement for the new org that had some public benefit language, and then see if we can make the case for becoming a (c)(3)....*

**Comment by mcollina** [comment]
I have way less concern about board representations if:

a. Node.js could potentially leave the foundation, if its leadership decides so.
b. The use of the Node.js brand is not limited to the foundation personnel.
c. Funds are managed with project involvement, and allocating XYZ to do ABC does not require a Board meeting (within limits).
d. Important decisions for the project are done at project level, not at the Board.

As @jasnell said, control over the Node.js brand has been used in the past to control its contributors. I think this is a situation that everybody that was (or was not) involved at that time would like to repeat. 
Based on the agreements done with Joyent when the Foundation was created, I do not think a) or maybe even b) is feasible for Node.js. This alone makes it a strong requirement for Board representation. It also makes Node.js a special snowflake within the multi-project foundation.

> If I understand @boneskull & others correctly - they want to work with organization staff on the items in 2) and have a clear path to provide feedback for 1) without the meeting obligations of a board seat. If decisions around project funding and branding/promotion are moved out of the Board's work into separate top-level committees, and projects have clear representation on those groups, does that strike the right balance of @mcollina @jasnell @boneskull et al?

@jorydotcom Overall I think it strikes the right balance, and we should work towards that goal _independently_ of Board representation. I believe Board representation is a must _unless_ the above point gets resolved.

**Comment by jorydotcom** [comment]
@mcollina fantastic context, thank you. That arrangement is different than what the projects have at JS Foundation. JSF holds some, but not all, of the project marks and doesn't weigh in on project branding issues except to help legally protect the mark (like the time we had someone doing some inappropriate things with the Grunt logo) and help order stickers from time to time. Our projects would expect that strategy to continue, and to be true for all projects I think.

@MylesBorins @mhdawson @hackygolucky: Could we get someone (or multiple someones) from the board to weigh in on these questions (slightly rephrased from Matteo)? Or maybe we can discuss them at the next meeting?

> a. Could Node.js or any foundation project leave the foundation, if its leadership decides so?
> b. Will the use of the Node.js or any foundation project brand be limited to the $Foundation or its personnel?
> c. Will projects be able to co-manage its funds, such that allocating XYZ to do ABC for the project does not require a Board meeting (within limits)?
> d. Does the Board expect to be able make important decisions for specific projects (beyond accepting it into the foundation and ensuring its compliance with policies)?
> 

There's probably some gray areas with all of these questions, but it would be ideal to confirm and capture the intent of the boards so we can reason about this more.

**Comment by jasnell** [comment]
I would put one small spin on question (a) above:

(A) Could Node.js or any foundation project leave the foundation, it is leadership decides so, *and* continue to use their associated brand. Specifically, if Node.js decided, at any point, to leave the Foundation, could it continue to irrevocably use the Node.js name and mark?

**Comment by rubys** [comment]
Meta comment: this is our (collective) foundation, not the board's.  We should endeavor to act like we own it.  By that, I mean that we should be focusing on proposing solutions, not asking questions.

> Could Node.js or any foundation project leave the foundation, if its leadership decides so?

First obvious observation: the code is open source, so forks can happen.  And people aren't chattel, so they can contribute where they wish.  So the question really comes down to brand.  And I see that as I composed this reply, @jasnell came to the same conclusion.

There are limits to which a 501(c)(6) can give away property which have commercial value (and brands clearly qualify here), but I don't think that will be the sticking point.

My sense is that even if the answer to the first question is "yes", that won't satisfy.  I think we need a concrete proposal as to how this could occur, and what it would involve.

> Will the use of the Node.js or any foundation project brand be limited to the $Foundation or its personnel?

Trademark law is complex, and this question has many layers.  There are parts where we need active participation of a lawyer who is well versed in trademark law.  There are parts that are best done by the projects themselves.  I would suggest [Apache PMC Branding Responsibilities](http://www.apache.org/foundation/marks/responsibility) as a potential starting point.

> Will projects be able to co-manage its funds, such that allocating XYZ to do ABC for the project does not require a Board meeting (within limits)?

I think it is time for these Foundations to start producing an annual budget where owners have allocated funds that they can use within the scope of their responsibility during the course of the year.

> d. Does the Board expect to be able make important decisions for specific projects (beyond accepting it into the foundation and ensuring its compliance with policies)?

My sense is that this question is too open ended.  In general, a board has few limits on what they can do.  For example, a board can decide to "retire" a project due to inactivity.  But a board that routinely acts that way will negatively impact the longevity of the foundation.  The normal model should be that projects and other committees propose and the board ratifies.

**Comment by MylesBorins** [comment]
From conversations I’ve been privy to I believe that any project can leave the foundation, but the IP / trademark stuff would need to be transferred to another 501(c)6 or 501(c)3. Someone please chime in if I’m incorrect.

Node.js is in a unique situation as the foundation does not of the trademark, so they would be unable to transfer it.

**Comment by jasnell** [comment]
I've opened a separate thread to discuss the trademark question: https://github.com/nodejs/bootstrap/issues/25

**Comment by boneskull** [comment]
@mcollina w/r/t trademark and Joyent, are you alluding to needing to rename the project “io.js”? Or is there something else I’m missing? don’t want to derail this but just wanted to make sure I understood the context.

**Comment by mcollina** [comment]
@boneskull I think the whole question will be answered on issue #25.

**Comment by dylans** [comment]
I will add that the story of Node.js and Joyent is one of if not the most important reason why open source foundations matter. There was some discussion earlier around what the purpose of a foundation is. It's important to have a neutral home for projects before a project becomes big and issues like this become contentious where one company tries to exert control and direction over a project.

For what it's worth (not much really), it's why we started the Dojo Foundation pretty much at the inception of Dojo in 2004 (the other reason being we didn't want to get personally served with legal notices like we were with the predecessor netWindows projects :) ), and why we encouraged so many projects over the years to join the effort, even projects that were considered by some to be direct competitors to existing foundation projects (I think it's silly to think of properly licensed and managed OSS projects as competitors because we share the same bigger goals).

For many years and even today, people doubt the value of software foundations, but Node.js and MySQL are just two of many examples where an OSS project has had tumultuous times when a company overexerted its control over a project. In my opinion this could have been avoided if the project trademark and copyright were placed in a foundation early on. It's too late to avoid that painful portion of Node.js' history, but hopefully the foundation can save future JS projects from similar struggles.

**Comment by MylesBorins** [comment]
From the last meeting it seemed like we had consensus across various stakeholders that we want to maintain community representation, but that it was a bit premature to figure out how that representation will be implemented until we understand the governance structure of the larger foundation. Some specific notes worth considering

* Proportional representation
  - currently 25% of our board is community reps
  - this is something that can be codified in the bylaws
     - likely anchored to platinum memerbship
* Prior art
  - the CNCF currently has a similar number of community reps on their board
  - a board seat is reserved for the largest project in the foundation

I'm going to remove the `bootstrap-agenda` label for now, until we have a bit of a better understanding of the foundation governance process. If anyone disagrees with this please re-add the label or ask me to

**Comment by MylesBorins** [comment]
@mcollina as we have appear to have consensus on two different approaches to board representation would you be open to closing this issue?

**Comment by mcollina** [comment]
Definitely, this was fixed a long time ago!
