### ISSUE TITLE
Results of Merger Poll for Node.js TSC and CommComm members

### ISSUE THREAD

**Issue by jasnell** [nodejs/bootstrap#24]
Over the past week I've been running an informal poll of @nodejs/tsc and @nodejs/community-committee members for the simple purpose of taking the "temperature of the room" with regards to the proposed merger. We had 29 responses, including 2 from non-TSC and non-CommComm members. I have removed the two non-top level committee member responses from the results. Note that there are currently 34 top level committee members so 27 is a solid representative sample. (Note that not every respondent provided answers to every question)

I will not provide the details of how each individual voted but the result charts are below along with a few notes...

![image](https://user-images.githubusercontent.com/439929/47435761-125e5280-d75a-11e8-9b08-87e4b4369255.png)

76% of the respondents feel that they understand the goals of the proposed merger. 20% indicate that they do not. That's a pretty solid ratio.

![image](https://user-images.githubusercontent.com/439929/47436000-7b45ca80-d75a-11e8-876f-facd0ee3fcc6.png)

Far more concerning is that 28% do not believe that the proposed merger will benefit Node.js (compared to 26% who believe that it will). Striking here is the 36% who are not yet sure. More on this in a bit.

![image](https://user-images.githubusercontent.com/439929/47436157-c9f36480-d75a-11e8-9ad2-1a212ab7926c.png)

In comparison, 72% believe that the proposed merger will benefit the JS Foundation projects, with 24% not sure.

![image](https://user-images.githubusercontent.com/439929/47436283-0b840f80-d75b-11e8-817c-a2799ca344e3.png)

52% believe that they understand the motivations for the timeline that has been proposed by the Boards for the merger. I think the more important bit here, however, is that the other 48% either aren't sure or do not understand the timing. My interpretation of this is that significantly more can be done to communicate the rationale for the proposed timing.

![image](https://user-images.githubusercontent.com/439929/47436446-60278a80-d75b-11e8-8865-b47626bf3561.png)

This is an interesting one, not only because the ratio of those who agree to those who disagree is effectively equal, but because *only* 36% of the respondents can say that they believe that the Foundation Board has adequately considered the needs of the project when evaluating the proposed merger.

![image](https://user-images.githubusercontent.com/439929/47436624-ae3c8e00-d75b-11e8-9950-af38621290c7.png)

This question is problematic for me. 57.7% of the respondents do not believe that the proposed merger would solve any existing problems in the Node.js project. More striking is that only 23% believe that it will.

![image](https://user-images.githubusercontent.com/439929/47436919-55b9c080-d75c-11e8-94db-9eddc7720cf2.png)

Equally striking are the number of respondents who believe that Node.js must have representation on the Foundation Board. As has been pointed out in a different discussion, this does not address the question of *why* folks believe that representation is needed, but it will be critical to address this point.

![image](https://user-images.githubusercontent.com/439929/47437017-8b5ea980-d75c-11e8-9805-0a2f5a77fdbf.png)

Back on the issue of the timeline. Only 28% believe that the merger should proceed on the current timeline, 32% saying that it should not. Before we advance further along with the current agenda, it's going to be important to address this and take another look at the proposed timeline.

![image](https://user-images.githubusercontent.com/439929/47437181-ded0f780-d75c-11e8-844a-887bb67a94a5.png)

This particular question is interesting not necessarily because only 20% of the respondents believe that the proposed merger would be good for the Gold and Silver level member companies, but because *nearly* all of those who said that it would be good are employed by Platinum member companies.

![image](https://user-images.githubusercontent.com/439929/47437298-29527400-d75d-11e8-8c3f-e6f3f30e1cb8.png)

This one goes along with the question about whether the proposed merger would solve any existing problems in the Node.js project. Only 20% believe that the merger would make it easier for the Foundation to provide additional resources to the project. Given that one of the arguments in favor of the merger has been that it would be *easier* to provide resources, there is obviously a discrepancy in expectations here that needs to be addressed.

![image](https://user-images.githubusercontent.com/439929/47437457-7e8e8580-d75d-11e8-9d69-8d3b30ee4f94.png)

The majority of respondents *definitely* have opinions about the proposed merger :-)

![image](https://user-images.githubusercontent.com/439929/47437519-9c5bea80-d75d-11e8-83af-657673afd676.png)

This is another striking response in that *only* 37.5% of the respondents believe that concerns have been adequately addressed. Whereas 33.3% believe that more can be done to address concerns and a significant 29.2% either aren't sure or don't have an opinion.

Overall, these results communicate that significantly more should be done to communicate the rationale, address the concerns, and establish the goals for the proposed merger among the Node.js top level committee members. The majority of Node.js top level committee members aren't yet seeing the benefits to the Node.js project but do recognize that the merger would likely be good for the JS Foundation projects.

**Comment by indexzero** [comment]
Thanks for organizing this @jasnell. The questions asked make this process out to be [a zero-sum game](https://en.wikipedia.org/wiki/Zero-sum_game), which is dangerous thinking imho. I firmly believe **this process is a non-zero sum game**. 

In other words: _the merged Foundation is greater than the sum of it's parts_ and as a result will create new unforeseen value through opportunities & synergy (yes, synergy).

When coming at these results from that perspective they are much more reasonable. For example, additional questions like these could have balanced the "zero-sum" nature of the questions that were asked:

- The proposed Foundation merger will create new opportunities.
- The proposed Foundation merger will expand the Node.js ecosystem.
- The proposed Foundation merger will benefit JavaScript.
- The proposed Foundation merger will attract new collaborators to the Node.js project.

**Comment by jasnell** [comment]
@indexzero ... fwiw, the questions asked were drawn directly from conversations I'd had with numerous top level committee members. I would not take any of the responses to indicate, "Hey! Don't do this merger thing!"... instead I would use it as an opportunity to see where the messaging and discussion around the proposal may need to apply additional focus and attention.

**Comment by mhdawson** [comment]
I agree with @indexzero that there is some potential for bias in terms of how the questions are phrased and how "Neither Agree nor Dis-Agree" is interpreted.  In any case interesting data to have.

**Comment by yorkie** [comment]
@jasnell color suggestion: we group the colors into the agreements, disagreements and none. The current version really hard to read :(

**Comment by refack** [comment]
> * The proposed Foundation merger will attract new collaborators to the Node.js project.

@indexzero, that also goes the other way, collaborators might shy away from a merged foundation (for varied reasons). Also AFAICT the foundation's impact on the number/diversity of new collaborators is minimal. For Node.js at least new collaborator recruitment and retention has been driven by the Org (i.e. the Body of current collaborators).

**Comment by hackygolucky** [comment]
I think this is great for folks to see what areas we need to make sure to do extra work in to make sure concerns are being heard and knowledge is being shared so there's a better understanding of all moving parts in this. Better understanding means informed stakeholders for better dialogue and healthy decision-making together.

A few things: a number of these questions assume that folks have a full understanding of how things work in a foundation and how things would work in detailed execution(will the proposed merger will make it easier to provide resources to the Node.js project), which hasn't been fully defined yet... As a person who has worked -at- the foundation, I was painfully aware of how many people didn't know how a foundation operates. I spent a fair amount of my time trying to break those barriers down and talk about how the sausage gets made so that folks could better understand the work they don't want to do but needs to get done in order to keep resources flowing for the org. Just like some developers don't concern themselves in what business value their coding contributions derive for the company that employs them. I think we all have to be honest here in that some folks care tremendously about these details! And some don't. So asking everyone in the committees to share opinions on things they may not have spent the time to learn about can send muddy signals in a survey. I don't discount that this is an area that both foundations need to make sure to invest more time in so that folks can't say they weren't able to find out information(as much as can be shared of any business, even a nonprofit). 

The elephant in the room to me in many of the conversations I have with folks individually and with many of the questions asked here is still --> "what value does a foundation bring to the Node.js project?" It's my belief and observation that we still have quite a bit of mismatch in expectations around what a foundation can and does provide and what is expected by Node.js project members with a foundation. A great example of this, as I've said prior, is who many of us are employed by and when we get to collaborate/contribute. We'd be programming in any other languages if the demand wasn't as high by lots of great employers for us to be working on Node.js.  The foundation and Board have done and continue to do a ton of work in this area(corp advocacy, networking, marketing, partnerships, etc) to get folks to pay many of us(not me these days) to do this work.  I'm happy to continue to have these conversations and chat one on one with people about what I think the answer to that question is. And I love to debate this!

**Comment by MylesBorins** [comment]
As we appear to have consensus in the bootstrap team around how board seats will be allocated I'm going to close this.  Feel free to re-open or let me know that I should if this was closed prematurely
